tunnel: crm-tunnel
credentials-file: /etc/cloudflared/creds.json
ingress:
  - hostname: arkhub.us
    service: http://ark-qbo-server.onrender.com
  - hostname: staging.arkhub.us
    service: http://ark-qbo-server-staging.onrender.com
  - service: http_status:404
